### ISSUE TITLE
Detected and ban chances

### ISSUE THREAD

**Issue by SatanicScripter** [TimoBlum/Counterstrafer#2]
Hem hello... i have a big question :D 
Is is detected? And there is a chance of get a ban for this?
Thanks man :3

**Comment by TimoBlum** [comment]
Hi, there is no chance of getting banned because it does not change anything in the games stats that would be noticeable and the only way this could be detected is if valorant checked for keys getting spammed too frequently, which this code doesnt do as it only reflects your agents movement for a standstill :D

**Comment by SatanicScripter** [comment]
To activate i have to press the central mouse button right? Thanks for the speedy response :D

**Comment by TimoBlum** [comment]
yes, the central mouse button toggles it on and off. have fun :)

**Comment by SatanicScripter** [comment]
And also i have only to run .py file (or have I to compile) ? Thanks for all
